"""add category to items

Revision ID: ea82e5b346b3
Revises: 8d1f0de7b6ca
Create Date: 2026-04-23 12:40:09.046462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea82e5b346b3'
down_revision: Union[str, Sequence[str], None] = '8d1f0de7b6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'category')
    # ### end Alembic commands ###
